// Edit these arrays to add projects and articles. All local paths are GitHub Pages compatible.
window.portfolio = {
projects: [
{ id:'louis-vuitton', name:'Louis Vuitton', subtitle:'A quieter kind of luxury.', category:'strategy', label:'BRAND STRATEGY', format:'17-SLIDE DECK', style:'lv', kicker:'Craft. Without Comment.', description:'A proposed route from visible status to understated craftsmanship, designed around the minimalist consumer.', context:'Academic group project · Tiffany Yuen, Genesis Reyes Casas, Isabella Segalla, Josh Meng, Tarun Lucas, and Roberto Saldivar.', challenge:'How could Louis Vuitton speak to consumers who value craft, restraint, and longevity over visible logos?', approach:'The team contrasted the existing prestige-led audience with a minimalist segment, then connected positioning to product, price, place, and promotion. The proposed creative direction paired material-first visuals with restrained copy and design-conscious media.', takeaway:'A new audience needs a coherent proposition: the product, the message, and the channel should all tell the same story.', file:'assets/louis-vuitton.pdf', image:'assets/louis-vuitton.jpg'},
{ id:'five-guys', name:'Five Guys', subtitle:'Let the experience do the talking.', category:'social', label:'SOCIAL & PROMOTION', format:'3-PAGE ANALYSIS', style:'five', kicker:'Good experiences.\nGreat word of mouth.', description:'A promotion analysis connecting customer experience, community, publicity, and a proposed media mix.', context:'Individual academic case analysis · Genesis Reyes. The original document notes AI assistance to polish the language of the author’s notes.', challenge:'How can a brand built on organic word of mouth grow without losing the experience that makes people recommend it?', approach:'The analysis examines publicity, social participation, local communication, and selective advertising. A hypothetical $100 million allocation prioritises social and community (30%), PR (25%), digital advertising (20%), experience and word of mouth (15%), and selective traditional media (10%).', takeaway:'A proposed allocation, not a managed campaign budget or a measured business result. The central recommendation is to amplify the customer experience while preserving it.', file:'assets/five-guys.pdf', image:'assets/five-guys.jpg'},
{ id:'headspace', name:'Headspace × Calm', subtitle:'Finding a distinctive voice in wellness.', category:'strategy', label:'POSITIONING & COMPETITION', format:'TEAM CASE STUDY', style:'headspace', kicker:'Same category.\nDifferent headspace.', description:'A comparative look at brand personality, partnerships, audience needs, and competitive positioning.', context:'Academic group project · Tiffany, Isabella, Josh, Roberto, Tarun, and Genesis.', challenge:'How do two mindfulness brands establish a different place in the audience’s mind?', approach:'The team compared Headspace’s approachable educational identity with Calm’s premium escape positioning, using a SWOT analysis and partnership examples. The assignment proposed a sleep-focused experience with evidence-led messaging.', takeaway:'Positioning becomes persuasive when the brand personality, audience need, and everyday use case reinforce one another. Recommendations reflect the assignment’s case context.', file:'assets/headspace.pdf', image:'assets/headspace.jpg'},
{ id:'arts-fashion', name:'Arts & Fashion', subtitle:'When prestige isn’t enough.', category:'culture', label:'CULTURE & BUSINESS', format:'18-SLIDE DECK', style:'arts', kicker:'The business\nof belonging.', description:'A presentation on strategic sensemaking, legitimacy, and the art market, centred on LVMH and Phillips.', context:'Academic group presentation · Mariam, Ninj, Genesis, and Shamsa.', challenge:'Why can a powerful luxury business struggle in a creative market?', approach:'The presentation applies scanning, interpreting, strategising, acting, and adjusting to the Phillips case. It explores trust, collector networks, symbolic value, and the limits of transferring a luxury strategy into art auctions.', takeaway:'Creative markets are shaped by relationships and cultural credibility as well as resources. The presentation connects brand thinking to the wider context of creative industries.', file:'assets/arts-fashion.pdf', image:'assets/arts-fashion.jpg'}
],
articles:[
{tag:'TECHNOLOGY & INNOVATION',title:'Youth Drives Innovation: Could Paraguay Be Latin America’s Silicon Valley?',text:'Young talent, local initiatives, and the possibilities of a growing digital ecosystem.',url:'https://asunciontimes.com/paraguay-news/tech-news/youth-drives-innovation-could-paraguay-be-latin-americas-next-silicon-valley/'},
{tag:'PEOPLE & CULTURE',title:'Paraguayan Students in Abu Dhabi: Bridging Cultures',text:'A story of education and cultural connection across continents.',url:'https://asunciontimes.com/people/paraguayan-students-in-abu-dhabi-bridging-cultures/'},
{tag:'DATA-DRIVEN REPORTING',title:'Safety in Asunción: A Data-Driven Look at Security in Paraguay’s Capital',text:'Putting a complex public conversation into context through reporting and data.',url:'https://asunciontimes.com/asuncion-city-guides/safety-in-asuncion-a-data-driven-look-at-security-in-paraguays-capital/'},
{tag:'INTERNATIONAL NEWS',title:'Paraguay’s Peace Boost: Safer Streets in the 2025 Global Peace Index',url:'https://asunciontimes.com/paraguay-news/international-news/paraguays-peace-boost-safer-streets-in-2025-global-peace-index/'},
{tag:'EXPLAINER',title:'How Paraguay Is Divided: Understanding Its Geopolitical Regions',url:'https://asunciontimes.com/paraguay-news/international-news/how-paraguay-is-divided-understanding-its-geopolitical-regions/'},
{tag:'SOCIETY',title:'Fertility Rate Trends in Paraguay and the World: How Do We Compare?',url:'https://asunciontimes.com/paraguay-news/national-news/fertility-rate-trends-in-paraguay-and-the-world-how-do-we-compare/'},
{tag:'ARTS & HUMAN RIGHTS',title:'Artists Invited to Human Rights Festival Reflejos in Argentina',url:'https://asunciontimes.com/paraguay-news/international-news/artists-invited-to-human-rights-festival-reflejos-in-argentina/'},
{tag:'EDUCATION & CITIES',title:'Registrations Open for Free Urban Planning Programme with International Accreditation',url:'https://asunciontimes.com/paraguay-news/national-news/registrations-open-for-free-urban-planning-programme-with-international-accreditation/'}
]};
