const {projects,articles}=window.portfolio;
const grid=document.querySelector('#projects');
const escapeHTML=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
projects.forEach((p,i)=>{const el=document.createElement('article');el.className='project';el.dataset.category=p.category;el.innerHTML=`<button class="project-open" data-id="${p.id}" aria-label="Explore ${escapeHTML(p.name)} case study"><div class="project-art ${p.style}"><div class="art-meta"><span>${p.label}</span><span>0${i+1}</span></div>${p.style==='lv'||p.style==='arts'?`<img src="${p.image}" alt="Cover of the ${escapeHTML(p.name)} presentation" loading="lazy">`:`<div class="graphic-type">${escapeHTML(p.kicker).replace('\n','<br>')}</div>`}<span class="open-circle" aria-hidden="true">↗</span></div><div class="project-title"><h3>${escapeHTML(p.name)}</h3><span>${p.format}</span></div><p>${p.subtitle}</p></button></article>`;grid.append(el)});
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});let count=0;grid.querySelectorAll('.project').forEach(p=>{p.hidden=b.dataset.filter!=='all'&&p.dataset.category!==b.dataset.filter;if(!p.hidden)count++});document.querySelector('#filter-status').textContent=`${count} projects shown`;}));
const dialog=document.querySelector('dialog');let lastTrigger;
grid.addEventListener('click',e=>{const b=e.target.closest('[data-id]');if(!b)return;lastTrigger=b;const p=projects.find(x=>x.id===b.dataset.id);document.querySelector('#dialog-content').innerHTML=`<p class="eyebrow">${p.label} / ACADEMIC WORK</p><h2 id="dialog-title">${p.name}</h2><p class="intro">${p.description}</p><p class="credits">${p.context}</p><img class="source-preview" src="${p.image}" alt="Original ${p.name} document cover"><h3>The question</h3><p>${p.challenge}</p><h3>The thinking</h3><p>${p.approach}</p><h3>The takeaway</h3><p>${p.takeaway}</p><a class="pill" href="${p.file}" target="_blank" rel="noopener noreferrer">Open original PDF ↗</a> <a class="download" href="${p.file}" download>Download PDF ↓</a>`;dialog.showModal();document.body.classList.add('modal-open');dialog.scrollTop=0;});
document.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});dialog.addEventListener('close',()=>{document.body.classList.remove('modal-open');lastTrigger?.focus()});
articles.forEach((a,i)=>{const link=document.createElement('a');link.className='article';link.href=a.url;link.target='_blank';link.rel='noopener noreferrer';link.innerHTML=`<span class="article-number">${String(i+1).padStart(2,'0')}</span><div><span class="eyebrow">${a.tag}</span><h3>${a.title}</h3>${a.text?`<p>${a.text}</p>`:''}<span class="publication">The Asunción Times</span></div><span class="article-arrow" aria-hidden="true">↗</span>`;document.querySelector(i<3?'#articles':'#more-articles').append(link)});

document.querySelector('#load-video').addEventListener('click',()=>{const frame=document.createElement('iframe');frame.title='Génesis on TikTok: A day as a Paraguayan student in Abu Dhabi';frame.src='https://www.tiktok.com/player/v1/7683976121838325013?autoplay=0&loop=0';frame.allow='fullscreen';frame.allowFullscreen=true;document.querySelector('#video-stage').replaceWith(frame);});
